server:
  port: 8888
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json

app:
  api-prefix: /api/v1

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${app.api-prefix}/user/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user
            - name: Retry
              args:
                name: default

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=${app.api-prefix}/shop/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: shopService
                fallbackUri: forward:/fallback/shop
            - name: Retry
              args:
                name: default

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: forward:/fallback/product
            - name: Retry
              args:
                name: default

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: cartService
                fallbackUri: forward:/fallback/cart
            - name: Retry
              args:
                name: default

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback/order
            - name: Retry
              args:
                name: default

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: postService
                fallbackUri: forward:/fallback/post
            - name: Retry
              args:
                name: default

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: notificationService
                fallbackUri: forward:/fallback/notification
            - name: Retry
              args:
                name: default

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: paymentService
                fallbackUri: forward:/fallback/payment
            - name: Retry
              args:
                name: default

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: fileService
                fallbackUri: forward:/fallback/file
            - name: Retry
              args:
                name: default

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=${app.api-prefix}/review/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: reviewService
                fallbackUri: forward:/fallback/review
            - name: Retry
              args:
                name: default

        - id: promotion-service
          uri: lb://promotion-service
          predicates:
            - Path=${app.api-prefix}/promotion/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: promotionService
                fallbackUri: forward:/fallback/promotion
            - name: Retry
              args:
                name: default

        - id: actuator
          uri: http://localhost:8888
          predicates:
            - Path=/actuator/**
          filters:
            - StripPrefix=2

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      userService:
        baseConfig: default
      productService:
        baseConfig: default
      cartService:
        baseConfig: default
      orderService:
        baseConfig: default
      shopService:
        baseConfig: default
      postService:
        baseConfig: default
      notificationService:
        baseConfig: default
      paymentService:
        baseConfig: default
      fileService:
        baseConfig: default
      reviewService:
        baseConfig: default
      promotionService:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 2s
    instances:
      userService:
        baseConfig: default
      productService:
        baseConfig: default
      cartService:
        baseConfig: default
      orderService:
        baseConfig: default
      shopService:
        baseConfig: default
      postService:
        baseConfig: default
      notificationService:
        baseConfig: default
      paymentService:
        baseConfig: default
      fileService:
        baseConfig: default
      reviewService:
        baseConfig: default
      promotionService:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
        cancel-running-future: true
      userService:
        timeout-duration: 10s
      productService:
        timeout-duration: 12s
      cartService:
        timeout-duration: 10s
      orderService:
        timeout-duration: 10s
      shopService:
        timeout-duration: 8s
      postService:
        timeout-duration: 12s
      notificationService:
        timeout-duration: 8s
      paymentService:
        timeout-duration: 10s
      fileService:
        timeout-duration: 12s
      reviewService:
        timeout-duration: 12s
      promotionService:
        timeout-duration: 12s

logging:
  level:
    root: INFO
    com.netflix.discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: api-gateway
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    exporter:
      zipkin:
        url: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0