server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: ${MYSQL_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: ${JWT_SIGNER_KEY_DEV}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

app:
  services:
    profile: http://localhost:8081/profile

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true