package com.tien.promotion.exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum ErrorCode {

      UNCATEGORIZED_EXCEPTION(9999, "UNCATEGORIZED_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
      INVALID_KEY(1001, "INVALID_KEY", HttpStatus.BAD_REQUEST),
      UNAUTHENTICATED(1002, "UNAUTHENTICATED", HttpStatus.UNAUTHORIZED),
      UNAUTHORIZED(1003, "UNAUTHORIZED", HttpStatus.FORBIDDEN),
      EXTERNAL_SERVICE_ERROR(1004, "EXTERNAL_SERVICE_ERROR", HttpStatus.FORBIDDEN),
      FILE_UPLOAD_FAILED(1005, "FILE_UPLOAD_FAILED", HttpStatus.SERVICE_UNAVAILABLE),
      SERVICE_UNAVAILABLE(1006, "SERVICE_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE),
      DATA_INTEGRITY_VIOLATION(1007, "DATA_INTEGRITY_VIOLATION", HttpStatus.BAD_REQUEST),
      DUPLICATE_ENTRY(1008, "DUPLICATE_ENTRY", HttpStatus.BAD_REQUEST),
      FOREIGN_KEY_VIOLATION(1009, "FOREIGN_KEY_VIOLATION", HttpStatus.BAD_REQUEST),
      FILE_SIZE_EXCEEDED(1010, "FILE_SIZE_EXCEEDED", HttpStatus.BAD_REQUEST),
      MISSING_REQUIRED_PARAMETER(1011, "MISSING_REQUIRED_PARAMETER", HttpStatus.BAD_REQUEST),
      SHOP_NOT_FOUND(1012, "SHOP_NOT_FOUND", HttpStatus.NOT_FOUND),
      PRODUCT_NOT_FOUND(1013, "PRODUCT_NOT_FOUND", HttpStatus.NOT_FOUND),
      PROMOTION_NOT_FOUND(1014, "PROMOTION_NOT_FOUND", HttpStatus.NOT_FOUND),
      PROMOTION_EXPIRED(1015, "PROMOTION_EXPIRED", HttpStatus.BAD_REQUEST),
      PROMOTION_USAGE_LIMIT_REACHED(1016, "PROMOTION_USAGE_LIMIT_REACHED", HttpStatus.BAD_REQUEST),
      CART_NOT_FOUND(1017, "CART_NOT_FOUND", HttpStatus.BAD_REQUEST),
      PRODUCT_NOT_ELIGIBLE_FOR_PROMO(1018, "PRODUCT_NOT_ELIGIBLE_FOR_PROMO", HttpStatus.BAD_REQUEST),
      NO_ELIGIBLE_PRODUCTS(1019, "NO_ELIGIBLE_PRODUCTS", HttpStatus.BAD_REQUEST),
      ORDER_VALUE_TOO_LOW(1020, "ORDER_VALUE_TOO_LOW", HttpStatus.BAD_REQUEST),
      ;

      int code;
      String message;
      HttpStatusCode statusCode;

}