server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
          - Path=${app.api-prefix}/profile/users/**
          filters:
          - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: order_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
        - id: payment_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2