server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: identityService
            - name: Retry
              args:
                name: default
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: profileService
            - name: Retry
              args:
                name: default
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: notificationService
            - name: Retry
              args:
                name: default
        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: productService
            - name: Retry
              args:
                name: default
        - id: order_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderService
            - name: Retry
              args:
                name: default
        - id: payment_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: paymentService
            - name: Retry
              args:
                name: default
        - id: cart_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: cartService
            - name: Retry
              args:
                name: default
        - id: shipping_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/shipping/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: shippingService
            - name: Retry
              args:
                name: default
        - id: actuator
          uri: http://localhost:8888
          predicates:
            - Path=/actuator/**

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      identityService:
        baseConfig: default
      profileService:
        baseConfig: default
      notificationService:
        baseConfig: default
      productService:
        baseConfig: default
      orderService:
        baseConfig: default
      paymentService:
        baseConfig: default
      cartService:
        baseConfig: default
      shippingService:
        baseConfig: default

  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 2s
    instances:
      identityService:
        baseConfig: default
      profileService:
        baseConfig: default
      notificationService:
        baseConfig: default
      productService:
        baseConfig: default
      orderService:
        baseConfig: default
      paymentService:
        baseConfig: default
      cartService:
        baseConfig: default
      shippingService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampler:
      probability: 1.0