spring:
  config:
    import: optional:configserver:http://config-server:9999
  application:
    name: service-discovery
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka