server:
  port: 8085
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/post-service?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  services:
    user: http://localhost:8080/user

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: post-service
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    exporter:
      zipkin:
        url: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0