server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  neo4j:
    uri: ${NEO4J_CONNECTION}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411