server:
  port: 8084
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  datasource:
    url: ${MYSQL_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    product: http://localhost:8083/product
    profile: http://localhost:8081/profile