server:
  port: 8083
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/product-service?authSource=admin