global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8888']

  - job_name: 'notification-service'
    metrics_path: '/notification/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'product-service'
    metrics_path: '/product/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'order-service'
    metrics_path: '/order/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']

  - job_name: 'payment-service'
    metrics_path: '/payment/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'cart-service'
    metrics_path: '/cart/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']

  - job_name: 'user-service'
    metrics_path: '/user/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']

  - job_name: 'post-service'
    metrics_path: '/post/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8089']

  - job_name: 'shop-service'
    metrics_path: '/shop/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8090']