server:
  port: 8086
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service
  redis:
    host: localhost
    port: 6379
    password: 12345678

app:
  services:
    product: http://localhost:8083/product
    order: http://localhost:8084/order