server:
  port: 8086
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service
  redis:
    host: localhost
    port: 6379
    password: 12345678

app:
  services:
    product: http://localhost:8083/product
    order: http://localhost:8084/order

resilience4j.circuitbreaker:
  instances:
    getProductPriceById:
      registerHealthIndicator: true
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
    existsProduct:
      registerHealthIndicator: true
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED

  retry:
    instances:
      getProductPriceById:
        maxRetryAttempts: 3
        waitDuration: 2s
      existsProduct:
        maxRetryAttempts: 3
        waitDuration: 2s