server:
  port: 8083
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service
  redis:
    host: localhost
    port: 6379
    password: 12345678

app:
  services:
    product: http://localhost:8082/product
    order: http://localhost:8084/order

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      getProductPriceById:
        baseConfig: default
      existsProduct:
        baseConfig: default
      createOrder:
        baseConfig: default

  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 2s
    instances:
      getProductPriceById:
        baseConfig: default
      existsProduct:
        baseConfig: default
      createOrder:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: cart-service
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    exporter:
      tempo:
        url: http://localhost:3200
    sampler:
      probability: 1.0